# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 625f27fa9e605359e747b482a3f075c8c5922049f06b1a28d2280965349ef986f249dd5992e2af99ac16856657eced71223c025a2864c9a8c6e4f6029bd010c9

test:
  secret_key_base: 7ed7bce6720b7c7ba43e10b5010f80c2a1cd3e03aa885103dcce68611682f6e3dcbf1679ed269e06d59bef98d0796e15b5d8817fd89fc21d71e6a1eebc0384ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
